// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDV0HArifNBNnaEdowW3kZ3SA46U94Xgrc',
    appId: '1:693900601684:web:aebcb0061359a79f67c0c1',
    messagingSenderId: '693900601684',
    projectId: 'navigationdrawerresq-aaff5d43',
    authDomain: 'navigationdrawerresq-aaff5d43.firebaseapp.com',
    storageBucket: 'navigationdrawerresq-aaff5d43.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCbZ4ILnqVEPGu0S-B3LgCAo8do-cTL-oM',
    appId: '1:693900601684:android:d32f352a2947082767c0c1',
    messagingSenderId: '693900601684',
    projectId: 'navigationdrawerresq-aaff5d43',
    storageBucket: 'navigationdrawerresq-aaff5d43.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAsaxP0DW2xFRtct6B_qrbRE1gTdhHmdwQ',
    appId: '1:693900601684:ios:34e349efbe9e65a067c0c1',
    messagingSenderId: '693900601684',
    projectId: 'navigationdrawerresq-aaff5d43',
    storageBucket: 'navigationdrawerresq-aaff5d43.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAsaxP0DW2xFRtct6B_qrbRE1gTdhHmdwQ',
    appId: '1:693900601684:ios:34e349efbe9e65a067c0c1',
    messagingSenderId: '693900601684',
    projectId: 'navigationdrawerresq-aaff5d43',
    storageBucket: 'navigationdrawerresq-aaff5d43.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDV0HArifNBNnaEdowW3kZ3SA46U94Xgrc',
    appId: '1:693900601684:web:18f69bebcce9811967c0c1',
    messagingSenderId: '693900601684',
    projectId: 'navigationdrawerresq-aaff5d43',
    authDomain: 'navigationdrawerresq-aaff5d43.firebaseapp.com',
    storageBucket: 'navigationdrawerresq-aaff5d43.firebasestorage.app',
  );

}